# Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
try:
    x = 5/0
    print("The result is: ".format(x))
except:
    print("Error: denominator should be a number ")
finally:
    print("Finally, The program run successfully")

Error: denominator should be a number 
Finally, The program run successfully


# Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [2]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in subjects:
    for j in verbs:
        for k in objects:
            x = i+" "+j+" "+k
            print(x)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [80]:
import numpy as np

In [83]:
def matric():
    a = np.array([1,2,3,4,5])
    N = int(input("Enter a number: "))
    arr = []
    for i in a:
        for k in range(1,N+1):
            arr.append(k**i)
    
    arr1 = np.array(arr)
    arr2 = arr1.ra = np.array([1,2,3,4,5])
print(len(a))eshape(5,5)
    arr1_transpose = np.transpose(arr2)
    print(arr1_transpose)
matric()


Enter a number: 5
[[   1    1    1    1    1]
 [   2    4    8   16   32]
 [   3    9   27   81  243]
 [   4   16   64  256 1024]
 [   5   25  125  625 3125]]


In [88]:
def matric():
    a = np.array([1,2,3,4,5])
    a1 = len(a)
    N = int(input("Enter a number: "))
    arr = []
    for i in a:
        for k in range(1,N+1):
            arr.append(k**i)
    
    arr1 = np.array(arr)
    arr2 = arr1.ra = np.array([1,2,3,4,5])
print(len(a))eshape(a1,N)
    arr1_transpose = np.transpose(arr2)
    print(arr1_transpose)
matric()

Enter a number: 3
[[  1   1   1   1   1]
 [  2   4   8  16  32]
 [  3   9  27  81 243]]
